# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- master

pool:
  vmImage: 'windows-latest'

steps:
- task: ArtifactoryDocker@1
  inputs:
    command: 'pull'
    artifactoryService: 'Artifactory'
    sourceRepo: 'docker'
    imageName: 'ustpoc-docker.jfrog.io/microsoft/dotnet-framework:4.7.2-sdk-windowsservercore-ltsc2016'
- task: Docker@2
  inputs:
    repository: 'ustpoc-docker-local.jfrog.io/windowsdockeragent'
    command: 'build'
    Dockerfile: '**/Dockerfile'
    tags: 'windowsdockeragent'
- task: ArtifactoryDocker@1
  inputs:
    command: 'push'
    artifactoryService: 'Artifactory'
    targetRepo: 'docker-local'
    imageName: 'ustpoc-docker-local.jfrog.io/windowsdockeragent:windowsdockeragent'
